# Generated by Django 5.1.2 on 2024-11-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_anime_status_alter_anime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Выберите статус'), ('ongoing', 'Онгоинг'), ('completed', 'Завершено'), ('announced', 'Анонс')], max_length=10, null=True, verbose_name='Статус аниме'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Выберите тип'), ('movie', 'Фильм'), ('tv', 'Тв Сериал'), ('ova', 'OVA'), ('ona', 'Спешл')], max_length=10, null=True, verbose_name='Тип аниме'),
        ),
    ]
